In [159]:
import requests
from bs4 import BeautifulSoup as BS
import pandas as pd

In [160]:
URL = 'https://www.pro-football-reference.com/years/2010/fantasy.htm'

In [161]:
pd.set_option('display.max_columns', None)

In [162]:
res = requests.get(URL)
soup = BS(res.content, 'html.parser')
table = soup.find('table', {'id': 'fantasy'})
df = pd.read_html(str(table))[0]
df.columns = df.columns.droplevel(level=0)

In [163]:
df.head()

,Rk,Player,Tm,FantPos,Age,G,GS,Cmp,Att,Yds,TD,Int,Att,Yds,Y/A,TD,Tgt,Rec,Yds,Y/R,TD,Fmb,FL,TD,2PM,2PP,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,1,Arian Foster*+,HOU,RB,24,16,13,0,0,0,0,0,327,1616,4.94,16,84,66,604,9.15,2,3,2,18,NaN,NaN,326,392.0,400.0,359.0,190,1,1
1,2,Adrian Peterson*,MIN,RB,25,15,15,0,0,0,0,0,283,1298,4.59,12,50,36,341,9.47,1,1,1,13,NaN,NaN,240,275.9,282.9,257.9,104,2,2
2,3,Jamaal Charles*+,KAN,RB,24,16,6,0,0,0,0,0,230,1467,6.38,5,64,45,468,10.40,3,3,2,8,NaN,NaN,238,282.5,290.5,260.0,102,3,3
3,4,Peyton Hillis,CLE,RB,24,16,14,1,2,13,0,0,270,1177,4.36,11,77,61,477,7.82,2,8,5,13,NaN,NaN,234,294.9,305.9,264.4,98,4,4
4,5,Chris Johnson*,TEN,RB,25,16,16,0,0,0,0,0,316,1364,4.32,11,57,44,245,5.57,1,3,2,12,NaN,NaN,229,272.9,280.9,250.9,93,5,5

In [164]:
#removing filler rows
df = df.loc[df['Player'] != 'Player']

In [165]:
#fixing player names that have astericks
df['Player'] = df['Player'].apply(lambda x: x.split('*')[0].strip())

In [166]:
#Column names:
#Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,PassingTD,PassingAtt,RushingYds,
#RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost

df['PassingYds'] = df['Yds'].iloc[:, 0]
df['RushingYds'] = df['Yds'].iloc[:, 1]
df['ReceivingYds'] = df['Yds'].iloc[:, 2]

df['PassingTD'] = df['TD'].iloc[:, 0]
df['RushingTD'] = df['TD'].iloc[:, 1]
df['ReceivingTD'] = df['TD'].iloc[:, 2]

df['PassingAtt'] = df['Att'].iloc[:, 0]
df['RushingAtt'] = df['Att'].iloc[:, 1]

In [167]:
df = df.rename(columns={
    'FantPos': 'Pos', 'PPR': 'FantasyPoints', 'Fmb': 'Fumbles', 'FL': 'FumblesLost'
})
df = df[[
    'Player','Tm','Pos','Age','G','GS','Tgt','Rec','PassingYds','PassingTD','PassingAtt',
    'RushingYds','RushingTD','RushingAtt','ReceivingYds','ReceivingTD','FantasyPoints',
    'Int','Fumbles','FumblesLost'
]]

In [168]:
df.to_csv('Yearly/2010.csv', index=False)